---
title: 'Tidy Tuesday Week 32: US Wind Turbine Data'
author: "Elizabeth Eisenhauer"
date: "11/5/2018"
output: html_document
---

This is the code behind an analysis of the "US Wind Turbine Data" dataset from the [#tidytuesday project](https://github.com/rfordatascience/tidytuesday/tree/master/data/2018-11-06). 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,error=FALSE,message=FALSE)

library(tidyverse)
library(readr)



```

```{r getdata, include=FALSE}
#get the data
data<-read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-11-06/us_wind.csv")

data_proc = data %>%
  select(t_ttlh,t_state,t_county) %>%
  arrange(desc(t_ttlh)) %>%
  unique() %>%
  head(5) %>%
  arrange(t_ttlh) %>%
  mutate(cs=paste(t_county, t_state, sep=", "))
```

Let's look at the counties with the 5 tallest wind turbines.

```{r}
data_proc %>%
  ggplot(aes(seq(1,5),t_ttlh)) +
  geom_col() +
  geom_text(aes(label=cs),vjust=-0.5) +
  geom_text(aes(label=paste(t_ttlh," m",sep="")),vjust=1.5)

ggsave("32_barplot.pdf",width=9,height=5)
```


