---
title: "#TidyTuesday Week 31: "
author: "Elizabeth Eisenhauer"
date: "10/29/2018"
output: html_document
---

This is the code behind an analysis of the "R and Package download stats" dataset from the [#tidytuesday project](https://github.com/rfordatascience/tidytuesday/tree/master/data/2018-10-30).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,error=FALSE,message=FALSE)

library(tidyverse)
library(scales)
library(broom)
library(ggthemes)
library(plotly)
library(ggplot2)
library(rworldmap)
library(countrycode)
library(plyr)

# Theme Edits
map_theme = theme_fivethirtyeight() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.x=element_blank(),
        panel.grid.major = element_blank())

```

```{r getdata, include=FALSE}
# the tidytuesday data
rdown <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-10-30/r-downloads.csv")

rdownyear <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018-10-30/r_downloads_year.csv")

rdown$region = countrycode(rdown$country, "iso2c", "country.name")
rdownyear$region = countrycode(rdownyear$country, "iso2c", "country.name")

rdownyear_processed <- rdownyear %>%
  select(date,time,size,version,os,country,region,ip_id)

#the map
map.world = map_data(map="world")
map.world$region[map.world$region=="USA"]<-"United States"
map.world$region[map.world$region=="UK"]<-"United Kingdom"
```

## What countries download R the most?

```{r}

## just on tidy tuesday
rdown %>%
  select(region,ip_id) %>%
  unique() %>%
  count('region')  %>%
  join(map.world,.,by='region') %>%
  select(region,freq,long,lat) %>%
  ggplot(aes(map_id=region, x=long, y=lat, fill=freq)) +
  geom_map(map=map.world) +
  scale_fill_gradient(low = "blue", high = "red", guide = "colourbar",trans="sqrt",breaks = c(1,10,100,300,500,700,900)) +
  coord_equal() +
  labs(title = "How many people downloaded R on #TidyTuesday of week 30?",
       subtitle = "(October 23, 2018)",
       caption = "source: cran-logs.rstudio.com") +
  map_theme +
  guides(fill=guide_colourbar(title="", barwidth = 15, barheight = 0.5)) +
  theme(plot.title = element_text(size=15)) 

## all last year - individual IP addresses
rdownyear_processed %>%
  select(region,ip_id) %>%
  unique() %>%
  count('region') %>%
  join(map.world,.,by='region') %>%
  select(region,freq,long,lat) %>%
  ggplot(aes(map_id=region, x=long, y=lat, fill=freq)) +
  geom_map(map=map.world) +
  scale_fill_gradient(low = "blue", high = "red", guide = "colourbar") +
  coord_equal() +
  labs(title = "How many unique IP addresses downloaded R this past year?",
       subtitle = "(October 20, 2017 - October 20, 2018)",
       caption = "source: cran-logs.rstudio.com") +
  map_theme +
  guides(fill=guide_colourbar(title="", barwidth = 15, barheight = 0.5))

ggsave("week31.1.png",width=8,height=6)

## all last year - all downloads
rdownyear_processed %>%
  select(region,ip_id) %>%
  count('region') %>%
  join(map.world,.,by='region') %>%
  select(region,freq,long,lat) %>%
  ggplot(aes(map_id=region, x=long, y=lat, fill=freq)) +
  geom_map(map=map.world) +
  scale_fill_gradient(low = "blue", high = "red", guide = "colourbar", breaks=c(100000,200000,300000), labels=comma) +
  coord_equal() +
  labs(title = "Total number of times R was downloaded this past year",
       subtitle = "(October 20, 2017 - October 20, 2018)",
       caption = "source: cran-logs.rstudio.com") +
  map_theme +
  guides(fill=guide_colourbar(title="", barwidth = 15, barheight = 0.5))

ggsave("week31.2.png",width=8,height=6)
```

## What countries downloaded R the most per capita?

Population data provided by World Development Indicators  (https://data.worldbank.org/indicator/SP.POP.TOTL), last updated 10/18/18.

```{r}
## get country population data
library(readr)
pop <- read_csv("~/Documents/Git/TidyTuesday/pop.csv")
pop$region = countrycode(pop$`Country Code`, "iso3c", "country.name")

gg = rdownyear_processed %>%
  select(region,ip_id) %>%
  unique() %>%
  count('region') %>%
  join(map.world,.,by='region') %>%
  join(.,pop,by='region') %>%
  select(region,freq,long,lat,Population2017) %>%
  mutate(percapita = 10000*(freq / Population2017))

ggplot(gg,aes(map_id=region, x=long, y=lat, fill=percapita)) +
  geom_map(map=map.world) +
  scale_fill_gradient(low = "blue", high = "red", guide = "colourbar", trans="sqrt",breaks = c(1,3,5,7,9,11,13)) +
  coord_equal() +
  labs(title = "What countries downloaded R the most per capita?",
       subtitle = "(October 20, 2017 - October 20, 2018)",
       caption = "Sources: cran-logs.rstudio.com and worldbank.org") +
  guides(fill=guide_colourbar(title="Downloads per 10,000 people:", barwidth = 15, barheight = 1)) +
  map_theme

ggsave("week31.3.png",width=8,height=6)

#just curious
head(gg[gg$region=='Iceland',])[1,]
head(gg[gg$region=='United States',])[1,]
head(gg[gg$region=='China',])[1,]
```

