---
title: 'First #TidyTuesday of 2019'
author: "Elizabeth Eisenhauer"
date: "12/31/2018"
output: 
  html_document:
    keep_md: TRUE
---


This is the code behind an analysis of the "#rstats and #TidyTuesday Tweets from rtweet" dataset from the [#tidytuesday project](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-01-01).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,error=FALSE)

library(tidyverse)
library(scales)
library(broom)
library(ggthemes)
library(plotly)

theme_set(theme_light())
```

```{r, include=FALSE}

githubURL <- ("https://github.com/rfordatascience/tidytuesday/blob/master/data/2019/2019-01-01/tidytuesday_tweets.rds?raw=true")
download.file(githubURL,"tidytuesday_tweets.rds")
tidytuesday <- read_rds("tidytuesday_tweets.rds")


githubURL <- ("https://github.com/rfordatascience/tidytuesday/blob/master/data/2019/2019-01-01/rstats_tweets.rds?raw=true")
download.file(githubURL,"rstats_tweets.rds")
rstats <- read_rds("rstats_tweets.rds")

```





